export const SET_TODOS_FROM_API = 'SET_TODOS_FROM_API';
export const ADD_NEW_TODO = 'ADD_NEW_TODO';
export const CHANGE_TODO_STATUS = 'CHANGE_TODO_STATUS';
export const DELETE_COMPLETED_TODOS = 'DELETE_COMPLETED_TODOS';
